config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "questions#index"

  concern :voteable do
    member do
      post :like
      post :dislike
    end
  end

  concern :commentable do
    resources :comments, only: :create
  end

  resources :questions, concerns: [:voteable, :commentable], shallow: true do
    resources :comments, only: :create 
    resources :answers, concerns: [:voteable, :commentable], except: [:show, :index] do
      post :best, on: :member
    end    
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy

  resources :badges, only: :index

  mount ActionCable.server => '/cable'

end

app/models/question.rb
class Question < ApplicationRecord
  include Voteable
  include Commentable

  belongs_to :author, class_name: 'User'
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable  
  has_one :badge, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :badge, reject_if: :all_blank

  validates :title, :body, presence: true  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!, except: [:index, :show]
  after_action :publish_question, only: [:create] 
  
  expose :questions, ->{ Question.all }
  expose :question, scope: ->{ Question.with_attached_files }  
  expose :answer, ->{ Answer.new }
  
  def show    
    gon.question_id = question.id
    gon.user_id = current_user ? current_user.id : 0
    answer.links.new    
  end

  def new
    question.links.new
    question.badge = Badge.new
  end

  def create
    @exposed_question = current_user.questions.new(question_params)
    if question.save
      redirect_to question, notice: 'Your question successfully created.'
    else      
      render :new
    end
  end

  def update    
    question.update(question_params) if author_of_question?
  end

  def destroy
    if author_of_question?
      question.destroy
      flash[:notice] = 'The question is successfully deleted.'
    end
    redirect_to questions_path
  end
  
  private

  def publish_question     
    return if question.errors.any?
    ActionCable.server.broadcast(
      'questions',
      question: question)
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [],
                                     links_attributes: [:id, :name, :url, :_destroy],
                                     badge_attributes: [:name, :image])
  end

  def author_of_question?
    current_user.author_of?(question)
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.slim
p class="question_#{question.id}"
  = link_to question.title, question
  = ' | ' 
  -if current_user&.author_of?(question)
    = link_to 'Delete', question, method: :delete

app/views/questions/_question_show.html.slim
h1= question.title
p= question.body

.question-score
  = render "votes/score", thing: question
  
- if question.files.attached?
  - question.files.each do |file|
    div class = "file_#{file.id}"
      p= link_to file.filename.to_s, url_for(file)
      -if current_user&.author_of?(question)
        p= link_to 'Delete file', attachment_path(file), method: :delete, remote: true

.links
  p Links:
  ul
    - question.links.each do |link|
      li class = "link_#{link.id}"
        p= link_to link.name, link.url
        -if link.gist?
          p= link.gist_content

.badge_question_place
  - if question.badge.present? && question.badge.answer.nil?
    = render question.badge       


= render "comments/comments", thing: question
        
-if current_user&.author_of?(question)
  = link_to 'Edit question', '#', class: 'edit-question-link'
  = form_with model: question, class: 'hidden question-form' do |f|
        = f.label :title, 'Title'
        = f.text_field :title
        = f.label :body, 'Question'
        = f.text_area :body
        = f.label :files
        = f.file_field :files, multiple: true, direct_upload: true
        #question_links
          = f.fields_for :links do |l|
            = render 'links/link_fields', f: l     
          .links
            = link_to_add_association 'Add link', f, :links, partial: 'links/link_fields' 
        = f.submit 'Save'

app/views/questions/index.html.slim
p= link_to 'Ask question', new_question_path

.questions-list
  = render questions
  
.test_jst

app/views/questions/new.html.slim
= render 'shared/errors', resource: question

= form_with model: question, local: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true

  p Links:
  #links
    = f.fields_for :links do |l|     
    .links
      = link_to_add_association 'Add link', f, :links, partial: 'links/link_fields'

  p Badge:
  p
    = f.fields_for :badge do |badge|
      p
        = badge.label :name, 'Badge name'
        = badge.text_field :name
      p
        = badge.label :image
        = badge.file_field :image, direct_upload: true
        
  p= f.submit 'Ask'

app/views/questions/show.html.slim
.question-errors
.question
  = render 'questions/question_show'

.answers
  = render question.answers.sorted_by_best
.answer-errors
  = render 'shared/errors', resource: answer
= form_with model: [question, answer], class: 'new-answer' do |f|
  p  
    = f.label :body, 'Your answer'
    = f.text_area :body
  p.files
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  p Links:
  #links
    = f.fields_for :links do |l|
    .links
      = link_to_add_association 'Add link', f, :links, partial: 'links/link_fields'
  p= f.submit 'Post your answer'

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: question %>');

<% unless question.errors.present? %>
  $('.question').html('<%= j render 'questions/question_show' %>');
<% end %> 