config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "questions#index"

  concern :voteable do
    member do
      post :like
      post :dislike
    end
  end

  concern :commentable do
    resources :comments, only: :create
  end

  resources :questions, concerns: [:voteable, :commentable], shallow: true do
    resources :comments, only: :create 
    resources :answers, concerns: [:voteable, :commentable], except: [:show, :index] do
      post :best, on: :member
    end    
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy

  resources :badges, only: :index

  mount ActionCable.server => '/cable'

end

app/models/answer.rb
class Answer < ApplicationRecord
  include Voteable
  include Commentable

  belongs_to :author, class_name: 'User'
  belongs_to :question
  has_many :links, dependent: :destroy, as: :linkable
  has_one :badge
  
  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :body, presence: true

  scope :sorted_by_best, -> { order(best: :desc, created_at: :asc) }

  def check_best!
    another_best = question.answers.where(best: true).first
    transaction do
      reward
      another_best.update!(best: false) if another_best && another_best != self
      self.update!(best: !best)
    end  
  end

  private

  def reward
    badge = question.badge
    badge.update!(answer: self, user: self.author) if badge 
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!
  after_action :publish_answer, only: [:create]

  expose :question
  expose :answer, scope: ->{ Answer.with_attached_files }

  def create
    @exposed_answer = question.answers.new(answer_params)
    answer.author = current_user
    answer.save
  end

  def destroy
    answer.destroy if current_user.author_of?(answer)
  end

  def update
    answer.update(answer_params) if current_user.author_of?(answer)
    @exposed_question = answer.question
  end

  def best
    answer.check_best! if current_user.author_of?(answer.question)
  end

  private

  def publish_answer
    return if answer.errors.any?
    AnswersChannel.broadcast_to(
      answer.question, 
      answer: answer,
      files: helpers.urls(answer.files),
      links: helpers.links(answer.links))
  end  

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:id, :name, :url, :_destroy])
  end  

end

app/helpers/answers_helper.rb
module AnswersHelper

  def urls(files)
    files.map do |file|
      { name: file.filename.to_s, url: url_for(file) }
    end
  end

  def links(links)
    links.map do |link|
      { name: link.name, 
        url: link.url,
        gist_content: link.gist? ? link.gist_content : '' }
    end
  end

end

app/views/answers/_answer.html.slim
-if answer.persisted?
  - best = answer.best ? ' best' : ''
  div class = "answer answer_#{answer.id}#{best}"
    - best_sign_classes = answer.best ? 'best-sign' : 'best-sign hidden'    
    div class = best_sign_classes
      = 'Best answer!'
    = answer.body
    -if current_user&.author_of?(question)
      = link_to 'Best', best_answer_path(answer),method: :post, remote: true
    -if current_user&.author_of?(answer)
      = link_to 'Delete', answer, method: :delete, remote: true
      = link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
      = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
        = f.label :body, 'Your answer'
        = f.text_area :body
        = f.label :files
        = f.file_field :files, multiple: true, direct_upload: true
        #answer_links
          = f.fields_for :links do |l|
            = render 'links/link_fields', f: l     
          .links
            = link_to_add_association 'Add link', f, :links, partial: 'links/link_fields'        
        = f.submit 'Save'
    
    .links
      p Links:
      ul
        - answer.links.each do |link|
          li class = "link_#{link.id}"
            p= link_to link.name, link.url
            -if link.gist?
              p= link.gist_content
    
    -if answer.files.attached?
      - answer.files.each do |file|
        div class = "file_#{file.id}"
          p= link_to file.filename.to_s, url_for(file)    
          -if current_user&.author_of?(answer)
            p= link_to 'Delete file', attachment_path(file), method: :delete, remote: true

    .badge_answer_place
      - if answer.badge.present?
        = render answer.badge

    .answer-score
      = render "votes/score", thing: answer

    = render "comments/comments", thing: answer

app/views/answers/best.js.erb
currentAnswer = $('<%= ".answer_#{answer.id}" %>');
currentAnswerBest = <%= answer.best? %> ;
checkBest(currentAnswer, currentAnswerBest);

<% if answer.best? && answer.badge %>
  placeForBadge = $('<%= ".answer_#{answer.id} .badge_answer_place" %>');
  moveBadge(placeForBadge);
<% end %>

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: answer %>');

<% if answer.persisted? %>
  $('.answers').append('<%= j render answer %>');
  $('.new-answer #answer_body').val('');
  $('.new-answer #links .link_name,.new-answer #links .link_url').val('');
  $('.new-answer #answer_files').val('').prop( "disabled", false );
  $('.new-answer .files input[type="hidden"]').remove();
<% end %> 

app/views/answers/destroy.js.erb
$('.answer_<%= answer.id %>').remove()	

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: answer %>');

<% unless answer.errors.present? %>  
  $('<%= ".answer_#{answer.id}" %>').replaceWith('<%= j render answer %>');
<% end %> 